"""
Sutura — deformation-field regression for non-rigid slice alignment.

A graph neural network reads the MOVING slice (expression PCA features + a kNN
spatial graph built on its warped coordinates with relative-position edge
features) and predicts a per-spot 2D displacement that maps each warped spot
back toward its original location:

    pred_xy = warped_xy + GNN(expr, warped_graph)
    loss    = || pred_xy - original_xy ||         (synthetic-warp ground truth)

Because warps are generated by src/warp_slice.apply_warp, the correspondence is
exact and free. Smooth warps are near-isometric; tears are discontinuous — the
GNN can in principle learn the discontinuity, which is where PASTE2 (GW/OT)
failed. Registration error is reported in pixels via src/scoring.py, so Sutura's
severity curve drops onto the same axes as results/headline_summary.png.

CPU-only. kNN graph is built with scipy (no torch_cluster dependency); message
passing uses PyG's native scatter fallback (no torch_scatter dependency).

Usage:
    python src/train.py                         # train + eval, default 151508
    python src/train.py --epochs 50 --hidden 96
"""

from __future__ import annotations

import argparse
import csv
from pathlib import Path

import anndata as ad
import numpy as np
import torch
import torch.nn as nn
from scipy.sparse import issparse
from scipy.spatial import cKDTree
from sklearn.decomposition import TruncatedSVD
from torch_geometric.nn import MessagePassing

from warp_slice import apply_warp
from scoring import registration_error_stats

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data"
RESULTS_DIR = ROOT / "results"


# --------------------------------------------------------------------------- #
# features & graph
# --------------------------------------------------------------------------- #
def expression_features(adata: ad.AnnData, dim: int, seed: int) -> np.ndarray:
    """Warp-invariant node features: TruncatedSVD of log-normalized counts."""
    X = adata.X
    X = X.tocsr().astype(np.float32) if issparse(X) else np.asarray(X, np.float32)
    # library-size normalize to 1e4, then log1p (keeps sparsity)
    counts = np.asarray(X.sum(1)).ravel()
    counts[counts == 0] = 1.0
    if issparse(X):
        X = X.multiply(1e4 / counts[:, None]).tocsr()
        X.data = np.log1p(X.data)
    else:
        X = np.log1p(X * (1e4 / counts[:, None]))
    svd = TruncatedSVD(n_components=dim, random_state=seed)
    Z = svd.fit_transform(X).astype(np.float32)
    Z = (Z - Z.mean(0)) / (Z.std(0) + 1e-6)        # standardize
    return Z


def knn_edges(coords: np.ndarray, k: int):
    """Symmetric kNN graph -> (edge_index [2,E], edge_attr [E,2] rel-pos)."""
    _, idx = cKDTree(coords).query(coords, k=k + 1)   # includes self at col 0
    src = np.repeat(np.arange(coords.shape[0]), k)
    dst = idx[:, 1:].reshape(-1)
    # symmetrize
    s = np.concatenate([src, dst])
    d = np.concatenate([dst, src])
    edge_index = np.stack([s, d])
    return edge_index, d, s


# --------------------------------------------------------------------------- #
# model
# --------------------------------------------------------------------------- #
class DeformConv(MessagePassing):
    """Message passing with relative-position edge features."""

    def __init__(self, dim: int):
        super().__init__(aggr="mean")
        self.msg = nn.Sequential(nn.Linear(2 * dim + 2, dim), nn.ReLU())
        self.upd = nn.Sequential(nn.Linear(2 * dim, dim), nn.ReLU())

    def forward(self, x, edge_index, edge_attr):
        out = self.propagate(edge_index, x=x, edge_attr=edge_attr)
        return self.upd(torch.cat([x, out], dim=-1))

    def message(self, x_i, x_j, edge_attr):
        return self.msg(torch.cat([x_i, x_j, edge_attr], dim=-1))


class SuturaNet(nn.Module):
    def __init__(self, feat_dim: int, hidden: int = 64, layers: int = 3):
        super().__init__()
        self.enc = nn.Linear(feat_dim, hidden)
        self.convs = nn.ModuleList([DeformConv(hidden) for _ in range(layers)])
        self.head = nn.Sequential(
            nn.Linear(hidden, hidden), nn.ReLU(), nn.Linear(hidden, 2))

    def forward(self, x, edge_index, edge_attr):
        h = torch.relu(self.enc(x))
        for conv in self.convs:
            h = h + conv(h, edge_index, edge_attr)      # residual
        return self.head(h)                             # per-node 2D displacement


# --------------------------------------------------------------------------- #
# one warped instance -> tensors
# --------------------------------------------------------------------------- #
def make_instance(adata, Z, severity, seed, tear, k, pitch):
    warped, gt = apply_warp(adata, severity, seed=seed, tear=tear)
    wxy = np.asarray(warped.obsm["spatial"], np.float32)
    oxy = np.asarray(gt["original_xy"], np.float32)
    edge_index, d, s = knn_edges(wxy, k)
    edge_attr = (wxy[d] - wxy[s]) / pitch              # relative position, pitch units
    target = (oxy - wxy) / pitch                       # displacement to recover, pitch units
    return {
        "x": torch.from_numpy(Z),
        "edge_index": torch.from_numpy(edge_index).long(),
        "edge_attr": torch.from_numpy(edge_attr.astype(np.float32)),
        "target": torch.from_numpy(target),
        "wxy": wxy, "oxy": oxy,
    }


def predicted_xy(model, inst, pitch):
    with torch.no_grad():
        pred = model(inst["x"], inst["edge_index"], inst["edge_attr"]).numpy()
    return inst["wxy"] + pred * pitch


# --------------------------------------------------------------------------- #
def main() -> None:
    p = argparse.ArgumentParser()
    p.add_argument("--sample", default="151508")
    p.add_argument("--epochs", type=int, default=40)
    p.add_argument("--steps-per-epoch", type=int, default=8)
    p.add_argument("--hidden", type=int, default=64)
    p.add_argument("--layers", type=int, default=3)
    p.add_argument("--knn", type=int, default=6)
    p.add_argument("--pca-dim", type=int, default=50)
    p.add_argument("--lr", type=float, default=1e-3)
    p.add_argument("--max-severity", type=float, default=8.0)
    p.add_argument("--tear-prob", type=float, default=0.5)
    p.add_argument("--val-severities", default="0,2,4,8")
    p.add_argument("--seed", type=int, default=0)
    p.add_argument("--out", default="arca_deform")
    args = p.parse_args()

    torch.manual_seed(args.seed)
    rng = np.random.default_rng(args.seed)

    src = DATA_DIR / f"DLPFC_{args.sample}.h5ad"
    if not src.exists():
        raise FileNotFoundError(f"{src} not found — run src/prepare_data.py first.")
    adata = ad.read_h5ad(src)
    coords = np.asarray(adata.obsm["spatial"], np.float32)
    pitch = float(np.median(cKDTree(coords).query(coords, k=2)[0][:, 1]))

    print(f"Sutura deform-regression | sample={args.sample} spots={adata.n_obs} "
          f"pitch={pitch:.1f}px")
    print("computing expression features (TruncatedSVD) ...")
    Z = expression_features(adata, args.pca_dim, args.seed)

    model = SuturaNet(args.pca_dim, args.hidden, args.layers)
    opt = torch.optim.Adam(model.parameters(), lr=args.lr)
    n_params = sum(p.numel() for p in model.parameters())
    print(f"model: {args.layers} layers, hidden={args.hidden}, params={n_params}")

    # fixed validation warps (seeds disjoint from training)
    val_sev = [float(x) for x in args.val_severities.split(",")]
    val_set = [(sv, make_instance(adata, Z, sv, seed=10_000 + i, tear=(sv > 0),
                                  k=args.knn, pitch=pitch))
               for i, sv in enumerate(val_sev)]

    print("\ntraining ...")
    for epoch in range(args.epochs):
        model.train()
        tot = 0.0
        for _ in range(args.steps_per_epoch):
            sev = float(rng.uniform(0, args.max_severity))
            tear = bool(rng.random() < args.tear_prob)
            inst = make_instance(adata, Z, sev, seed=int(rng.integers(1, 9999)),
                                 tear=tear, k=args.knn, pitch=pitch)
            opt.zero_grad()
            pred = model(inst["x"], inst["edge_index"], inst["edge_attr"])
            loss = (pred - inst["target"]).norm(dim=1).mean()   # px/pitch units
            loss.backward()
            opt.step()
            tot += loss.item()
        if epoch % 5 == 0 or epoch == args.epochs - 1:
            model.eval()
            msg = []
            for sv, inst in val_set:
                pxy = predicted_xy(model, inst, pitch)
                st = registration_error_stats(pxy, inst["oxy"])
                msg.append(f"sev{sv:g}:{st['median']:5.0f}px")
            print(f"  epoch {epoch:3d} | train L={tot/args.steps_per_epoch:.3f} "
                  f"pitch | val median reg-err  " + "  ".join(msg))

    # final eval -> curve CSV (overlay on headline axes) + checkpoint
    RESULTS_DIR.mkdir(parents=True, exist_ok=True)
    model.eval()
    rows = []
    for sv, inst in val_set:
        pxy = predicted_xy(model, inst, pitch)
        st = registration_error_stats(pxy, inst["oxy"])
        rows.append({"severity": sv, "reg_err_median": st["median"],
                     "reg_err_mean": st["mean"], "reg_err_p90": st["p90"],
                     "n": st["n"]})
    csv_path = RESULTS_DIR / f"{args.out}_curve.csv"
    with open(csv_path, "w", newline="") as fh:
        w = csv.DictWriter(fh, fieldnames=list(rows[0].keys()))
        w.writeheader()
        w.writerows(rows)
    ckpt = RESULTS_DIR / f"{args.out}.pt"
    torch.save({"state_dict": model.state_dict(), "args": vars(args),
                "pitch": pitch}, ckpt)

    print(f"\nSutura val registration error (median px), tears for sev>0:")
    for r in rows:
        print(f"  sev {r['severity']:>4}: {r['reg_err_median']:7.1f} px median "
              f"| {r['reg_err_mean']:7.1f} px mean")
    print(f"\nwrote curve -> {csv_path}")
    print(f"wrote ckpt  -> {ckpt}")
    print("NOTE: this eval is SELF-frame (recover warped 151508's OWN original "
          "coords). PASTE2's comparable self-mode baseline is ~0px (it exploits "
          "identical expression). The headline tear curve (658->838px) is the "
          "CROSS task vs 151507 — a fair head-to-head needs a two-slice Sutura "
          "variant or a matched cross-frame eval. Do NOT read these as a win.")


if __name__ == "__main__":
    main()
